version: '3.8'

services:
  web:
    build: .
    ports:
      - "5123:5123"
    volumes:
      - .:/app  # Mount the entire current directory to the container's /app
      - registrations-db:/app/instance  # Mount a named volume for the database
    environment:
      - FLASK_APP=app.py
    restart: always

volumes:
  registrations-db:
