version: '3.8'

services:
  web:
    build: .
    ports:
      - "5123:5123"
    volumes:
      - .:/app  # Mount the entire current directory to the container's /app
      - registrations-db:/app/instance  # Mount a named volume for the database
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0  # Set the host to 0.0.0.0 for external access
      - FLASK_RUN_PORT=5123  # Set the port to 5123

    restart: always

volumes:
  registrations-db: